service: klug-saver

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  environment:
    DYNAMODB_TABLE_EXPENSE: ${self:service}-${opt:stage, self:provider.stage}-expense
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_EXPENSE}"

functions:
  create:
    handler: expense/create.create
    events:
      - http:
          path: expense
          method: post
          cors: true
  batchCreate:
    handler: expense/batchCreate.batchCreate
    events:
      - http:
          path: batch-create
          method: post
          cors: true

  list:
    handler: expense/list.list
    events:
      - http:
          path: expense
          method: get
          cors: true
          parameters:
            querystrings:
              from: false

  # update:
  #   handler: expense/update.update
  #   events:
  #     - http:
  #         path: expense/{id}
  #         method: put
  #         cors: true

  delete:
    handler: expense/delete.delete
    events:
      - http:
          path: expense/{id}
          method: delete
          cors: true

resources:
  Resources:
    ExpensesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE_EXPENSE}
